version: "3.9"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/workspace
        depends_on:
            - redis
            - rabbitmq
        environment:
            - FLASK_ENV
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - DISCLAIMER
            - ALLOWED_WEBHOOKS_FILE

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/workspace
        depends_on:
            - redis
            - rabbitmq
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - ALLOWED_WEBHOOKS_FILE
        command: rq worker --url redis://redis:6379 -c worker-settings

    subscriber:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/workspace
        depends_on:
            - redis
            - rabbitmq
        environment:
            - RABBITMQ_CONSUME_QUEUE=teaching-action.digital-resources
            - SERVICE_URL=localhost:4000
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=guest
            - RABBITMQ_PASSWORD=guest
        command: python src/events/rabbitmq/subscriber_worker.py

    redis:
        image: redis
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:4.0-management
        ports:
            - "5672:5672"   # RabbitMQ default port
            - "15672:15672" # Management UI port
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
