version: '2'
services:
    waas-api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/workspace
        depends_on:
            - redis
    redis:
        image: redis


