services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/workspace
        depends_on:
            - redis
        env_file:
            - .env

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/workspace
        depends_on:
            - redis
        env_file:
            - .env
        command: rq worker --url redis://redis:6379 -c worker-settings

    subscriber:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/workspace
        depends_on:
            - redis
        env_file:
            - .env
        environment:
            - PYTHONPATH=/workspace
        command: python src/events/rabbitmq/subscriber_worker.py

    redis:
        image: redis
        ports:
            - "6379:6379"
