openapi: 3.0.0
info:
  title: Transcription Service API
  description: API documentation for the WAAS application.
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
    description: Local server
paths:
  /transcribe:
    post:
      summary: Transcribe audio
      description: Transcribe audio using Whisper with optional callbacks and filename parameters.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      parameters:
        - name: model
          in: query
          schema:
            type: string
            enum:
              - tiny
              - base
              - large
            default: tiny
        - name: task
          in: query
          schema:
            type: string
            enum:
              - translate
              - transcribe
            default: transcribe
        - name: language
          in: query
          schema:
            type: string
          description: Language of the transcription (optional).
        - name: email_callback
          in: query
          schema:
            type: string
          description: Email for job completion notifications.
        - name: webhook_id
          in: query
          schema:
            type: string
          description: Webhook ID for job completion notifications.
        - name: filename
          in: query
          schema:
            type: string
            default: untitled-transcription
          description: Name of the file to be transcribed.
      responses:
        '201':
          description: Transcription job created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    description: ID of the created job.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.
  /jobs/{job_id}:
    get:
      summary: Get job status
      description: Fetch the status and details of a transcription job.
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job status and details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  meta:
                    type: object
                  origin:
                    type: string
                  func_name:
                    type: string
                  args:
                    type: array
                    items:
                      type: string
                  result:
                    type: object
                  enqueued_at:
                    type: string
                    format: date-time
                  started_at:
                    type: string
                    format: date-time
                  ended_at:
                    type: string
                    format: date-time
        '404':
          description: Job not found.
  /download/{job_id}:
    get:
      summary: Download transcription results
      description: Download the results of a completed transcription job in various formats.
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
        - name: output
          in: query
          schema:
            type: string
            enum:
              - srt
              - vtt
              - json
              - txt
              - timecode_txt
              - jojo
            default: srt
      responses:
        '200':
          description: Transcription results.
        '400':
          description: Invalid output format.
        '404':
          description: Job not found.
  /queue:
    get:
      summary: Get queue size
      description: Get the current number of jobs in the queue.
      responses:
        '200':
          description: Queue size retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Number of jobs in the queue.
  /stats:
    get:
      summary: Get transcription statistics
      description: Retrieve statistics on total transcription time.
      responses:
        '200':
          description: Transcription statistics retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_time_transcribed:
                    type: string
                    description: Total transcription time.
  /detect:
    post:
      summary: Detect language
      description: Detect the language of an uploaded audio file.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      parameters:
        - name: model
          in: query
          schema:
            type: string
            enum:
              - tiny
              - base
              - large
            default: tiny
      responses:
        '200':
          description: Language detected successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detectedLanguage:
                    type: string
                  languageCode:
                    type: string
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.
  /debug-sentry:
    get:
      summary: Debug Sentry
      description: Endpoint to trigger a Sentry error for testing.
      responses:
        '500':
          description: Intentional error triggered.
